version: '3'

services:

  frontend:
    container_name: lead-frontend
    restart: always
    build: ./frontend
    ports:
      - 8000:8000
    depends_on:
      - backend
      - db
    environment:
      API_URL: http://backend:1337
    command: ./docker-entrypoint.sh

  backend:
    container_name: lead-cms
    build: ./backend
    restart: always
    ports:
      - 1337:1337
    environment:
      DATABASE_CLIENT: ${DB_CLIENT}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASS}
      DATABASE_SSL: 'false'
    depends_on:
      - db
    command: ./docker-entrypoint.sh

  db:
    container_name: lead-db
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - data:/var/lib/mysql
     
  adminer:
    container_name: lead-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data: